name: monkor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

# ADD THIS FLUTTER LAUNCHER ICONS CONFIGURATION
flutter_icons:
  android: true
  ios: true
  image_path: "assets/1.jpg"
  # Remove the web section or set to false if you don't need it

flutter:
  uses-material-design: true
  
  assets:
    - assets/hanja.json
    - assets/korean.json
    - assets/1.jpg  # Make sure your icon is also included in assets